[development]
SQLALCHEMY_DATABASE_URI = "postgresql://minha_viola:m1nh4v10l4@localhost/minha_viola"

[testing]
SQLALCHEMY_DATABASE_URI = "postgresql://minha_viola:m1nh4v10l4@localhost/minha_viola_test"